# Generated by Django 5.1 on 2026-02-17 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='leagues/', verbose_name='Logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['sport', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='bi-trophy', help_text='Classe do Bootstrap Icons', max_length=50, verbose_name='Ícone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200, verbose_name='Time da Casa')),
                ('away_team', models.CharField(max_length=200, verbose_name='Time Visitante')),
                ('home_logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Logo Casa')),
                ('away_logo', models.ImageField(blank=True, null=True, upload_to='teams/', verbose_name='Logo Visitante')),
                ('start_time', models.DateTimeField(verbose_name='Início')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('live', 'Ao Vivo'), ('finished', 'Encerrado'), ('cancelled', 'Cancelado'), ('postponed', 'Adiado')], default='scheduled', max_length=20, verbose_name='Status')),
                ('home_score', models.IntegerField(default=0, verbose_name='Placar Casa')),
                ('away_score', models.IntegerField(default=0, verbose_name='Placar Visitante')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('result', models.CharField(blank=True, help_text='home, away ou draw', max_length=20, verbose_name='Resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='betting.league', verbose_name='Liga')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'unique_together': {('event', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Odd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Vitória Casa, Empate, Vitória Visitante', max_length=200, verbose_name='Seleção')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Odd')),
                ('selection_key', models.CharField(help_text='home, draw, away, over, under, yes, no', max_length=50, verbose_name='Chave')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='betting.market', verbose_name='Mercado')),
            ],
            options={
                'verbose_name': 'Odd',
                'verbose_name_plural': 'Odds',
                'ordering': ['market', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Apostado')),
                ('odd_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Odd no Momento')),
                ('potential_win', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganho Potencial')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('won', 'Ganha'), ('lost', 'Perdida'), ('cancelled', 'Cancelada'), ('cashout', 'Cash Out')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data da Aposta')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Liquidada em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('odd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='betting.odd', verbose_name='Odd')),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leagues', to='betting.sport', verbose_name='Esporte'),
        ),
    ]
