# Generated by Django 5.1 on 2026-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(blank=True, default='', help_text='Nonce para autenticação Web3', max_length=100, verbose_name='Nonce'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Endereço Ethereum (MetaMask)', max_length=42, null=True, unique=True, verbose_name='Endereço Wallet'),
        ),
    ]
