# Generated by Django 5.1 on 2026-02-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.CharField(choices=[('ETH', 'Ethereum (ETH)'), ('USDT', 'Tether (USDT)'), ('USDC', 'USD Coin (USDC)'), ('BTC', 'Bitcoin (BTC)'), ('MATIC', 'Polygon (MATIC)')], max_length=10, verbose_name='Criptomoeda')),
                ('network', models.CharField(choices=[('ethereum', 'Ethereum Mainnet'), ('polygon', 'Polygon'), ('bsc', 'BNB Smart Chain'), ('arbitrum', 'Arbitrum')], default='ethereum', max_length=20, verbose_name='Rede')),
                ('amount_crypto', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Valor Crypto')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor USD')),
                ('tx_hash', models.CharField(max_length=66, unique=True, verbose_name='TX Hash')),
                ('from_address', models.CharField(max_length=42, verbose_name='Endereço Origem')),
                ('to_address', models.CharField(max_length=42, verbose_name='Endereço Destino')),
                ('confirmations', models.IntegerField(default=0, verbose_name='Confirmações')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirming', 'Confirmando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to='wallet.wallet', verbose_name='Carteira')),
            ],
            options={
                'verbose_name': 'Depósito Crypto',
                'verbose_name_plural': 'Depósitos Crypto',
                'ordering': ['-created_at'],
            },
        ),
    ]
